version: "3"

services:
  omeka-web:
    container_name: apache-php
    build:
      context: .
    restart: always
    ports:
      - 80:80
    volumes:
      - ./files:/usr/src/omeka-s/files
      - ./logs:/usr/src/omeka-s/logs
      - ./modules:/usr/src/omeka-s/modules
      - ./themes:/usr/src/omeka-s/themes
    environment:
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_CONNECTION_TYPE=${EMAIL_CONNECTION_TYPE}
    depends_on:
      - omeka-db

  omeka-db:
    container_name: mariadb
    image: mariadb:10.4
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
