theme: jekyll-theme-minimal
title: Omeka S Dockerized
description: Omeka S is a web publishing platform for digital cultural heritage collections.
logo: android-chrome-512x512.png
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
