version: '3'

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@gudon.ch"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    env_file: .env
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  omeka-web:
    container_name: apache-php
    build:
      context: .
      args:
       - OMEKA_VERSION=v2.1.1
    volumes:
    - ./files:/var/www/html/omeka-s/files
    - ./database.ini:/var/www/html/omeka-s/config/database.ini
    env_file: .env
    depends_on:
      - omeka-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`museum.gudon.ch`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

  omeka-db:
    container_name: mariadb
    image: mariadb:10.4
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    env_file: .env

  omeka-db-admin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=omeka-db
    depends_on:
      - omeka-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`museum-db.gudon.ch`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"